# ANN Classification — 10 Preprocessing Steps

1. **Import Required Libraries**
   - Pandas, train_test_split, StandardScaler, LabelEncoder, pickle.

2. **Load the Dataset**
   - Read `Churn_Modelling.csv` using `pd.read_csv()`.

3. **Drop Irrelevant Columns**
   - Remove `RowNumber`, `CustomerId`, and `Surname`.

4. **Encode Gender**
   - Use `LabelEncoder` to convert Gender into numerical values.

5. **One-Hot Encode Geography**
   - Convert Geography categories into separate binary columns.

6. **Get Feature Names**
   - Use `get_feature_names_out()` to obtain the encoded column names.

7. **Combine Encoded Columns**
   - Convert the encoded array into a DataFrame and combine it with the original data, removing the original Geography column.

8. **Save the Encoders**
   - Save `label_encoder_gender` and `onehot_encoder_geo` using `pickle`.

9. **Separate and Split the Data**
   - `X` = independent features; `y` = dependent target (`Exited`).
   - Split into 80% training and 20% testing data.

10. **Scale and Save the Scaler**
    - Use `StandardScaler`: `fit_transform()` on training data and `transform()` on testing data.
    - Save the fitted scaler as `scaler.pkl`.

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [3]:
## Load the dataset
data = pd.read_csv("2.Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Preprocess the Data
## Drop irrelent columns
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
## Remember: OneHotEncoder converts categorical features into numerical representations without implying that one category is greater than another.
## Encode Categorical variable (to make Gender in numerical value)
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender']) # "fit" Learns the necessary information from the data. "transform" Uses that learned information to transform the data. fit_transform does both.
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
## OneHot encode "Geography"

from sklearn.preprocessing import OneHotEncoder
oneHotEncoder = OneHotEncoder(sparse_output=False) # sparse matrix
# oneHotEncoder = OneHotEncoder() # dense array
geography_encoded = oneHotEncoder.fit_transform(data[["Geography"]])
geography_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
print(geography_encoded[:10])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]

In [8]:
# see what features are specifically i have 
oneHotEncoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
# the feature we can get from geography columns is connecting with the geography encoded vector of Geography column
geo_encoded_df = pd.DataFrame(geography_encoded, columns=oneHotEncoder.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
## Combine one hot encoder columns with the original data(Remove the original text-based Geography column and replace it with the three numerical one-hot encoded columns.)
## Important: geo_encoded_df must already exist as a DataFrame.
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data
# ignore the error as already Geography column dropped

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [11]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [12]:
## Save the encoder and the scaler
with open('label_encoder_gender.pkl','wb') as file: 
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(oneHotEncoder, file)

### ANN Data Preprocessing

- `X` → Independent features (inputs).
- `y` → Dependent feature (target/output).
- `train_test_split()` → Splits data into training (80%) and testing (20%) sets.
- `fit_transform()` → Learns scaling statistics and scales training features.
- `transform()` → Scales testing features using the same training statistics.

In [13]:
# Divide the dataset into dependent and independent features
X = data.drop('Exited', axis=1)
y = data['Exited']

## Split the data in testing and training sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [15]:
with open('scaler.pkl', 'wb') as file :
    pickle.dump(scaler, file)

### ANN Implementation

In [16]:
%pip show tensorflow

Name: tensorflow
Version: 2.15.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/darshan-mandaviya/Documents/Coding/Krish_Naik/python/11_ANN_CLASSIFICATION/venv/lib/python3.11/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [17]:
import sys
print(sys.executable)
print(sys.version)

/home/darshan-mandaviya/Documents/Coding/Krish_Naik/python/11_ANN_CLASSIFICATION/venv/bin/python
3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]

In [18]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

2026-10-19 14:35:35.178200: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-10-19 14:35:35.673914: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-10-19 14:35:35.673982: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-10-19 14:35:35.760479: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-10-19 14:35:35.962676: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-10-19 14:35:35.967083: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-10-19 14:35:37.550959: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [19]:
X_train.shape
# X_test.shape # (2000, 12)

(8000, 12)

In [20]:
## Build our ANN Model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1], )),
    Dense(32, activation='relu'), ## HL2
    Dense(1, activation='sigmoid') ## output layer
])

2026-10-19 14:35:39.235562: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-10-19 14:35:39.237867: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [22]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [23]:
## Compile the model
model.compile(
    optimizer=opt,  # Use the Adam optimizer to update the model's weights
    loss="binary_crossentropy",  # Measure prediction error for binary classification
    metrics=['accuracy']  # Track accuracy during training and evaluation
)

In [24]:
## Set up TensorBoard
# TensorBoard visualizes logs and metrics collected during model training
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard # Import callbacks for training monitoring and control

log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S") # Create a timestamped directory path for training logs
tensorflow_callback = TensorBoard(
    log_dir=log_dir, # Save TensorBoard logs in the specified directory
    histogram_freq=1 # Record weight and bias histograms after each epoch
)

In [25]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10,restore_best_weights=True)

In [26]:
### Train the Model
history = model.fit(
    X_train,y_train,validation_data=(X_test, y_test), epochs=100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3996 - accuracy: 0.8319 - val_loss: 0.3543 - val_accuracy: 0.8560
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3540 - accuracy: 0.8539 - val_loss: 0.3531 - val_accuracy: 0.8570
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3474 - accuracy: 0.8585 - val_loss: 0.3397 - val_accuracy: 0.8645
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3464 - accuracy: 0.8584 - val_loss: 0.3402 - val_accuracy: 0.8640
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3419 - accuracy: 0.8602 - val_loss: 0.3479 - val_accuracy: 0.8605
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8622 - val_loss: 0.3459 - val_accuracy: 0.8630
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3363 - accuracy: 0.8635 - val_loss: 0.3525 - val_accuracy: 0.8620
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3338 - accuracy: 0.8639 - val_loss: 0.3532 - val_accuracy: 0.8550
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3318 - accuracy: 0.8639 - val_loss: 0.3451 - val_accuracy: 0.8585
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3282 - accuracy: 0.8621 - val_loss: 0.3487 - val_accuracy: 0.8600
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3266 - accuracy: 0.8641 - val_loss: 0.3514 - val_accuracy: 0.8620
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3259 - accuracy: 0.8646 - val_loss: 0.3433 - val_accuracy: 0.8650
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3214 - accuracy: 0.8660 - val_loss: 0.3499 - val_accuracy: 0.8605

In [27]:
model.save('model.h5')

/home/darshan-mandaviya/Documents/Coding/Krish_Naik/python/11_ANN_CLASSIFICATION/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [28]:
## Load TensorBoard Extension
# Magic command to load the TensorBoard extension
%load_ext tensorboard

In [31]:
# %tensorboard --logdir logs/fit
%tensorboard --logdir logs/fit20261019-110504

Reusing TensorBoard on port 6006 (pid 10142), started 0:00:21 ago. (Use '!kill 10142' to kill it.)

In [30]:
import os

print("Log directory:", log_dir)
print("Exists:", os.path.exists(log_dir))

for root, dirs, files in os.walk(log_dir):
    for file in files:
        print(file)

Log directory: logs/fit20261019-143539
Exists: True
events.out.tfevents.1792400739.darshan-mandaviya-Precision-7520.5193.0.v2
events.out.tfevents.1792400740.darshan-mandaviya-Precision-7520.5193.1.v2